spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: lab-3
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# Book Metadata API (OpenLibrary)
book:
  metadata:
    api:
      url: https://openlibrary.org
      timeout: 5